
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Mon Oct 09 17:14:07 PDT 2000
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int PLUS = 2;
  static final int MINUS = 3;
  static final int TIMES = 4;
  static final int NUMBER = 10;
  static final int LPAREN = 7;
  static final int VARIABLE = 9;
  static final int EOF = 0;
  static final int error = 1;
  static final int UMINUS = 6;
  static final int RPAREN = 8;
  static final int DIVIDE = 5;
}

